### ISSUE TITLE
Bug with display and feature request

### ISSUE THREAD

**Issue by g-pane** [stooged/PS4-Dongle#1]
Hi,
First, thanks. I'm using your ESP32 S2 version and now i have the new dongle.
Now i have a problem and two feature request

1) The display option not work, i have try with the library version (TFT_eSPI 2.5.43 and .34), the display is simply white. No text on the screen.
2) Is possible to autoload the goldhen.bin automatically when open the page?
3) Is possible to load internally the goldhen without sdcard? I don't like the unsupported fat32 message, or at least use exFAT for the sdcard
4) Why you don't use the exfat image from this source?
https://gbatemp.net/threads/better-usb-image-for-ps4-hack.618293/

Don't have the error message, i have used for your S2 version, and work as the same
Thanks, i'm waiting your response. Have a nice day

**Comment by stooged** [comment]
1 = you have to setup the espi lib to work with the s3 dongle or use the one linked in the source which has been setup to use it.

2 = it could be done if i ever find the time.

3 = with this project i decided to not go with an internal hen because it is problematic for people to update and the purpose of this project is to have a usb like dongle.
if you wish to implement an internal hen method you can look at [ESP32-Server-900u](https://github.com/stooged/ESP32-Server-900u) and copy the code over.

4= there is no point in using an image to simply remove a popup message on the console, it has no effect on the exploit success rate.
the console does not care so it is purely aesthetic, the exfathax.h is kept to a minimum to preserve memory of the esp8266 or esp32 which allows it to operate on as many board types as possible.

i post the complete sources so you can make the changes you desire.

**Comment by g-pane** [comment]
1) I have resolved it, thanks! I have take the library from the original source with copy-paste.
2) I can do a pull request for this, i'll do it, i'll make an HTML so every one can autoload goldhen.bin
3) I have try to use the internal one but i don't know where make the change. Pratically i'd like a file uploader like the ESP32-Server-900u on the internal memory
4) I have already do the updated exfathax.h, i know is purely aesthetic. If you want, i can make a pull request also for this
